import Navbar from '@/components/Layout/Header';
import Skills from '@/components/Skills';
import Socials from '@/components/Socials';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />
      <h1 className='mt-4 text-5xl font-extrabold'>
        Hi I&apos;m <span className='text-blue-500'>Arif</span>
      </h1>
      <p className='text-lg mt-2'>
        Web developer. Developing UI and featureful web applications with React
        and nodeJS.
      </p>
      <Socials />
      <Skills />
    </>
  );
};

export default Home;
